#!/usr/bin/python
from peewee import *
import csv

import sys
sys.path.insert(0, "/home/anna/bioinformatics/ngs/py_scripts/")
from common_helpers.make_outdir import file_from_path, make_outdir, new_file
from common_helpers.parse_csv import parse_csv
from blast.classes.blast_parser import BlastParser

class BaseModel(Model):
    class Meta:
        database = db

class Protein(BaseModel):
    seq_id = CharField()
    description = TextField(null=True)
    fasta = TextField()
    organism = CharField()
    source = CharField()

class BlastHit(BaseModel):
	subject_id = CharField()
	query_id = CharField()






db_path = '/home/anna/bioinformatics/euglenozoa/mitoproteome.db'

db = SqliteDatabase(db_path)

csv_data = parse_csv(csv_path, delimiter=delimiter)